name: release
on:
  workflow_dispatch:
jobs:
  master-branch:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.106

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./src

      - name: Generate icons
        run: dotnet run --configuration Release --project .\BasaltHexagonsIconsGenerator\BasaltHexagonsIconsGenerator.csproj -- --output-directory ../icons

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./icons
          git commit -m "Automated changes by GitHub Actions, update generated icons."

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.REPO_PUSH }}

  non-master-branch:
    if: ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Show failure message
        run: core.setFailed('Release workflow can only work on `master` branch, current is ${{ github.ref }}'')
